"""コンバータ設定"""

HOVER_SPEED_THRESHOLD_MS = 0.3
HOVER_MIN_DURATION_SEC = 5
CAMERA_YAW_THRESHOLD_DEG = 15
TRACK_INTERVAL_SEC = 1
FT_TO_M = 0.3048
SRT_TIMEZONE_OFFSET_HOURS = 9
SCHEMA_VERSION = "1.0.0"
GEOCODE_CACHE_PRECISION = 4
